version: "3.0"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code:z
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc4-alpine
    volumes:
      - ./data:/data:z
